abstract class AppState  {}
class InitialAppState extends AppState{}
class AppChangeBottomNavBarState extends AppState{}
class AppCreateDatabaseState extends AppState{}
class AppInsertDatabaseState extends AppState{}
class AppGetDatabaseState extends AppState{}
class AppChangeBottomSheetState extends AppState{}
class AppGetDatabaseLoadingState extends AppState{}
class AppUpdateDataBaseState extends AppState{}
class AppDeleteDataBaseState extends AppState{}
